name: 'WordPress Plugin Check'
on:
  pull_request:
  push:
    branches:
    - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
    
    - name: Build plugin
      run: |
        ./build.sh dev
        mkdir tmp-build
        unzip build-dev.zip -d tmp-build

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        build-dir: './tmp-build'
        exclude-directories: 'vendor'